### ISSUE TITLE
Inverted AO/Broken shadows on AMD/Mesa

### ISSUE THREAD

**Issue by AkashiiKun** [ruvaldak/VanillaBean-shaders#18]
![javaw_P5HZ1c9LXc](https://user-images.githubusercontent.com/44606942/132550215-2ea7b883-7f19-4008-a7c9-8d461e655e14.png)
![javaw_77dfkIR3ZO](https://user-images.githubusercontent.com/44606942/132550223-a8c1ef4b-c67f-4232-a4e9-b7157a3dafd6.png)

**Comment by ruvaldak** [comment]
:omegaconcern:

**Comment by ruvaldak** [comment]
Worth testing again please. I don't own Mesa or AMD ot test this. Might have to go back a few commits, maybe ccc28b9b138640e811d1ec032845d64c45b2e2cb, cus I think I broke SSAO somehow in some of the latest commits lmao

**Comment by AkashiiKun** [comment]
Sure, will test it soon.

**Comment by AkashiiKun** [comment]
Seems that the issue has been fixed.
![image](https://user-images.githubusercontent.com/44606942/179677430-b9c856ef-e2f5-42b9-83b1-7e16d44b26cf.png)

**Comment by ruvaldak** [comment]
thank you for testing. Glad it has been fixed. Gonna close this issue, but if anything crops up again, it can be reopened.
