### ISSUE TITLE
Add Enhanced Fog (a la Comp's Border Fog, SimpleTAA dog)

### ISSUE THREAD

**Issue by TrillionDeTurtle** [ruvaldak/VanillaBean-shaders#21]
I feel like it would fit in to the shader (if its possible with shaders)
there is a mod that also does it called fade in chunks (https://github.com/Johni0702/fade-in-chunks)

**Comment by ruvaldak** [comment]
Afaik this is impossible shader-side. Best thing that could be done is completely replacing fog with something more like SimpleTAA or Complementary's Border Fog.
