### ISSUE TITLE
Held items and entities are broken on intel gpus with iris

### ISSUE THREAD

**Issue by notLily72** [ruvaldak/VanillaBean-shaders#22]
As it appears in iris
https://cdn.discordapp.com/attachments/998782672413405196/998965950965620888/unknown.png
https://cdn.discordapp.com/attachments/998782672413405196/998966080217292840/unknown.png

If the files:
- gbuffers_hand.fsh
- gbuffers_hand.vsh
- gbuffers_entities.fsh
- gbuffers_entities.vsh

are deleted it becomes this
https://cdn.discordapp.com/attachments/998782672413405196/998977725949808843/unknown.png

**Comment by ruvaldak** [comment]
supposedly fixed by 53b2eb3. Reopen if it crops up again please. Intel is very strict it seems.
