### ISSUE TITLE
Stars appear underwater

### ISSUE THREAD

**Issue by Mangoiz** [ruvaldak/VanillaBean-shaders#24]
Vanilla
![image](https://user-images.githubusercontent.com/107194826/180565593-4a577dc2-6e9b-4d6f-9dd3-f55fd9578f3d.png)

Bean
![image](https://user-images.githubusercontent.com/107194826/180565669-4fd0b1d4-6664-4599-a7d8-4bada129e64d.png)

Also, it looks like theirs every so slightly less water fog with Bean

**Comment by ruvaldak** [comment]
yee I'm using a very different fog calculation. I'll be tackling that soon.

**Comment by ruvaldak** [comment]
fixed in ~~59af4b2~~ c208037314f4fa5d0737c5c8d03e099843fc810b
